name: Chess Move
description: Submit a chess move
title: "chess|"
labels: ["move"]
body:
  - type: markdown
    attributes:
      value: |
        Please write your move in the **title** of this issue, right after `chess|` (for example, `chess|e2e4`).
