name: Chess Move
description: Submit a chess move
title: "chess|e2e4"
labels: ["move"]
body:
  - type: input
    id: move
    attributes:
      label: Move (in UCI format)
      description: The move you want to play. E.g., e2e4
      placeholder: e2e4
    validations:
      required: true
