name: Best Move

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  best-move:
      runs-on: ubuntu-latest
      permissions: write-all
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r chess/requirements.txt

        - name: Execute best move
          id: execute_best_move
          run: |
            output=$(python chess/chess-best-move.py)
            echo "output=$output" >> $GITHUB_OUTPUT

  call-issue-move:
      uses: ./.github/workflows/issue-move.yml
      with:
          move: ${{ needs.best-move.outputs.output }}