name: Execute Chess Move

on:
  issues:
    types: [opened]

jobs:
  execute-move:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    if: startsWith(github.event.issue.title, 'chess|')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r chess/requirements.txt

    - name: Extract move from issue title
      id: extract_move
      run: |
        echo "::set-output name=move::$(echo '${{ github.event.issue.title }}' | cut -d'|' -f2)"

    - name: Execute chess move
      id: execute_move
      run: |
        result=$(python chess/chess-controller.py ${{ steps.extract_move.outputs.move }})
        echo "::set-output name=result::$result"

    - name: Add response comment to the issue
      uses: actions/github-script@v7
      with:
        script: |
            octokit.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ${{ steps.execute_move.outputs.result }}
            })

    - name: Close the issue
      uses: actions/github-script@v7
      with:
        script: |
          github.issues.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            state: "closed"
          });