name: Execute Chess Move

on:
  issues:
    types: [opened]

jobs:
  execute-move:
    runs-on: ubuntu-latest
    permissions: write-all
    if: startsWith(github.event.issue.title, 'chess|')
    concurrency:
      group: chess
      cancel-in-progress: true
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r chess/requirements.txt

    - name: Extract move from issue title
      id: extract_move
      run: echo "move=$(echo '${{ github.event.issue.title }}' | cut -d'|' -f2)" >> $GITHUB_OUTPUT

    - name: Execute chess move
      id: execute_move
      run: |
        output=$(python chess/chess-controller.py ${{ steps.extract_move.outputs.move }})
        echo "output=$output" >> $GITHUB_OUTPUT

    - name: Close Issue
      uses: peter-evans/close-issue@v3
      with:
        comment: ${{ steps.execute_move.outputs.output }}

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: ${{ steps.execute_move.outputs.output }}
  respond-on-cancel:
    runs-on: ubuntu-latest
    needs: execute-move
    if: ${{ needs.execute-move.result != 'success' }}
    steps:
      - name: Close Issue if workflow is running
        uses: peter-evans/close-issue@v3
        with:
          comment: 'There is currently a move in progress, please try again later.'