name: Handle Chess Move Failure

on:
  workflow_run:
    workflows: ["Execute Chess Move"]
    types:
      - failed
      - cancelled

jobs:
  comment-on-failure:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Get Issue Number
        id: get_issue
        run: |
          ISSUE_NUMBER=$(gh run view ${{ github.event.workflow_run.id }} --json event | jq -r '.event.issue.number')
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ env.issue_number }}
          comment: '⚠️ The chess move execution has failed. Try again later.'
          labels: |
            wontfix
          close-reason: 'not_planned'